### ISSUE TITLE
Test_add: No.of Request Limit

### ISSUE THREAD

**Issue by jonathanrjpereira** [ewenchou/bluetooth-proximity#1]
Whenever I execute the test_address.py script with a specified number of requests/loops, I get the RSSI values. 
But I have obeserved that if the number of requests/loops is greater than 32, the values after the 32nd loop are always zero. I was wondering if there is some sort of timeout associated with this.

**Comment by ewenchou** [comment]
I have seen similar behavior on my Raspberry Pi 2. It seems related to the actual hardware because if I reboot the Pi it goes away. I also tried removing other things plugged into the Pi's USB ports as well, and that seems to help the problem. So it could be power related as well. Unfortunately, it was beyond my knowledge to find the root cause.
