### ISSUE TITLE
bluetooth_scanner.py returning rssi of 0 after around 15 iterations

### ISSUE THREAD

**Issue by jord1242** [ewenchou/bluetooth-proximity#12]
First off, great code, works like a charm! I have it sending the RSSI of certain bluetooth via API, but when I run the bluetooth_scanner.py code, it polls correctly for only around 15 iterations, anything after that always returns 0.

Has anyone experienced anything like this? I am not seeing any errors. Appreciate any help you can provide.

PS - This is running on a raspberry pi.

JJ

**Comment by ewenchou** [comment]
I also found that after X number of iterations it keeps returning zero value. I couldn't figure out the root cause of the problem but I did a couple of things to work around it.

1) Increase the time between polls
2) After doing above, I still would get into the zero-value problem after running it long enough, so I added a cronjob to reboot my Raspberry Pi nightly.

**Comment by Lasse05** [comment]
Hey , 
do you have a new solution for this issue? Or any idea where the problem is?
I am running your code on pi zero.
Best regards and i look forward to your reply!
Edit : my solve is to restart the system bus from the pi
